CREATE TABLE PERSON(ID INT PRIMARY KEY, FIRSTNAME VARCHAR(64), LASTNAME VARCHAR(64));
CREATE TABLE EVENT(ID INT PRIMARY KEY AUTO_INCREMENT, DESCRIPTION VARCHAR(64));

CREATE TABLE PERSON_EVENT (PERSON_ID INT,EVENT_ID INT,FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID),FOREIGN KEY(EVENT_ID) REFERENCES EVENT(ID));