INSERT INTO PERSON (ID,FIRSTNAME,LASTNAME) VALUES (1,'DIHUI','BAO');
INSERT INTO PERSON (ID,FIRSTNAME,LASTNAME) VALUES (2,'YELU','CHEN');

INSERT INTO EVENT (DESCRIPTION) VALUES ('MID-AUTUMN DAY');
INSERT INTO EVENT (DESCRIPTION) VALUES ('NATIONAL DAY');

INSERT INTO PERSON_EVENT (PERSON_ID,EVENT_ID) SELECT 1,id FROM EVENT WHERE description='MID-AUTUMN DAY';
INSERT INTO PERSON_EVENT (PERSON_ID,EVENT_ID) SELECT 2,id FROM EVENT WHERE description='MID-AUTUMN DAY';
INSERT INTO PERSON_EVENT (PERSON_ID,EVENT_ID) SELECT 2,id FROM EVENT WHERE description='NATIONAL DAY';